// <auto-generated />
using System;
using Chord_Finder_Core.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chord_Finder_Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Chord_Finder_Core.Model.Chord", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChordTypeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ChordTypeID");

                    b.ToTable("Chords");
                });

            modelBuilder.Entity("Chord_Finder_Core.Model.ChordType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ChordTypes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("6c9ea46b-9625-4bef-bc6e-ee72da9ae732"),
                            Description = "A chord with a root, major third, and perfect fifth.",
                            Name = "Major"
                        },
                        new
                        {
                            ID = new Guid("fcc4ea0f-1545-4fa8-a759-a26d9cf24486"),
                            Description = "A chord with a root, minor third, and perfect fifth.",
                            Name = "Minor"
                        },
                        new
                        {
                            ID = new Guid("aabd075a-b201-473b-ad0f-d0d875ef1584"),
                            Description = "A chord with a root, minor third, and diminished fifth.",
                            Name = "Diminished"
                        },
                        new
                        {
                            ID = new Guid("b289393b-d8e7-4db7-bf1d-d83caaf71704"),
                            Description = "A chord with a root, major third, and augmented fifth.",
                            Name = "Augmented"
                        },
                        new
                        {
                            ID = new Guid("be08b4ae-f8f1-4518-bfec-f71b009a6006"),
                            Description = "A chord with a root, major third, perfect fifth, and minor seventh.",
                            Name = "Dominant Seventh"
                        },
                        new
                        {
                            ID = new Guid("53fb45c9-8bb9-492e-9dac-258a460621cc"),
                            Description = "A chord with a root, major third, perfect fifth, and major seventh.",
                            Name = "Major Seventh"
                        },
                        new
                        {
                            ID = new Guid("ddd178b1-1421-4d3c-a21d-ce1bd63ee8c7"),
                            Description = "A chord with a root, minor third, perfect fifth, and minor seventh.",
                            Name = "Minor Seventh"
                        },
                        new
                        {
                            ID = new Guid("b449187c-cd70-4ca3-bd1d-3a5152d8b13c"),
                            Description = "A chord with a root, minor third, diminished fifth, and minor seventh.",
                            Name = "Half-Diminished"
                        },
                        new
                        {
                            ID = new Guid("c7e1c758-87a8-4c00-9445-be26e069ec14"),
                            Description = "A chord with a root, minor third, diminished fifth, and diminished seventh.",
                            Name = "Diminished Seventh"
                        },
                        new
                        {
                            ID = new Guid("46c55a1e-f908-421a-8079-8abba03f5869"),
                            Description = "A chord with a root, major second, and perfect fifth.",
                            Name = "Suspended Second"
                        },
                        new
                        {
                            ID = new Guid("8d5f188c-d027-46d4-b4e8-5ed944bab598"),
                            Description = "A chord with a root, perfect fourth, and perfect fifth.",
                            Name = "Suspended Fourth"
                        });
                });

            modelBuilder.Entity("Chord_Finder_Core.Model.Note", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("Frequency")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000100000000"),
                            Frequency = 16.350000000000001,
                            Name = "C0"
                        },
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000200000000"),
                            Frequency = 32.700000000000003,
                            Name = "C1"
                        },
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000300000000"),
                            Frequency = 65.409999999999997,
                            Name = "C2"
                        },
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000400000000"),
                            Frequency = 130.81,
                            Name = "C3"
                        },
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000500000000"),
                            Frequency = 261.63,
                            Name = "C4"
                        },
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000600000000"),
                            Frequency = 523.25,
                            Name = "C5"
                        },
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000700000000"),
                            Frequency = 1046.5,
                            Name = "C6"
                        },
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000800000000"),
                            Frequency = 2093.0,
                            Name = "C7"
                        },
                        new
                        {
                            ID = new Guid("00000001-0000-0000-0000-000900000000"),
                            Frequency = 4186.0100000000002,
                            Name = "C8"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000100000000"),
                            Frequency = 17.32,
                            Name = "C#0/Db0"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000200000000"),
                            Frequency = 34.649999999999999,
                            Name = "C#1/Db1"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000300000000"),
                            Frequency = 69.299999999999997,
                            Name = "C#2/Db2"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000400000000"),
                            Frequency = 138.59,
                            Name = "C#3/Db3"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000500000000"),
                            Frequency = 277.18000000000001,
                            Name = "C#4/Db4"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000600000000"),
                            Frequency = 554.37,
                            Name = "C#5/Db5"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000700000000"),
                            Frequency = 1108.73,
                            Name = "C#6/Db6"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000800000000"),
                            Frequency = 2217.46,
                            Name = "C#7/Db7"
                        },
                        new
                        {
                            ID = new Guid("00000002-0000-0000-0000-000900000000"),
                            Frequency = 4434.9200000000001,
                            Name = "C#8/Db8"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000100000000"),
                            Frequency = 18.350000000000001,
                            Name = "D0"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000200000000"),
                            Frequency = 36.710000000000001,
                            Name = "D1"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000300000000"),
                            Frequency = 73.420000000000002,
                            Name = "D2"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000400000000"),
                            Frequency = 146.83000000000001,
                            Name = "D3"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000500000000"),
                            Frequency = 293.66000000000003,
                            Name = "D4"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000600000000"),
                            Frequency = 587.33000000000004,
                            Name = "D5"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000700000000"),
                            Frequency = 1174.6600000000001,
                            Name = "D6"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000800000000"),
                            Frequency = 2349.3200000000002,
                            Name = "D7"
                        },
                        new
                        {
                            ID = new Guid("00000003-0000-0000-0000-000900000000"),
                            Frequency = 4698.6300000000001,
                            Name = "D8"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000100000000"),
                            Frequency = 19.449999999999999,
                            Name = "D#0/Eb0"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000200000000"),
                            Frequency = 38.890000000000001,
                            Name = "D#1/Eb1"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000300000000"),
                            Frequency = 77.780000000000001,
                            Name = "D#2/Eb2"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000400000000"),
                            Frequency = 155.56,
                            Name = "D#3/Eb3"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000500000000"),
                            Frequency = 311.13,
                            Name = "D#4/Eb4"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000600000000"),
                            Frequency = 622.25,
                            Name = "D#5/Eb5"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000700000000"),
                            Frequency = 1244.51,
                            Name = "D#6/Eb6"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000800000000"),
                            Frequency = 2489.02,
                            Name = "D#7/Eb7"
                        },
                        new
                        {
                            ID = new Guid("00000004-0000-0000-0000-000900000000"),
                            Frequency = 4978.0299999999997,
                            Name = "D#8/Eb8"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000100000000"),
                            Frequency = 20.600000000000001,
                            Name = "E0"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000200000000"),
                            Frequency = 41.200000000000003,
                            Name = "E1"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000300000000"),
                            Frequency = 82.409999999999997,
                            Name = "E2"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000400000000"),
                            Frequency = 164.81,
                            Name = "E3"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000500000000"),
                            Frequency = 329.63,
                            Name = "E4"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000600000000"),
                            Frequency = 659.25,
                            Name = "E5"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000700000000"),
                            Frequency = 1318.51,
                            Name = "E6"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000800000000"),
                            Frequency = 2637.02,
                            Name = "E7"
                        },
                        new
                        {
                            ID = new Guid("00000005-0000-0000-0000-000900000000"),
                            Frequency = 5274.04,
                            Name = "E8"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000100000000"),
                            Frequency = 21.829999999999998,
                            Name = "F0"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000200000000"),
                            Frequency = 43.649999999999999,
                            Name = "F1"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000300000000"),
                            Frequency = 87.310000000000002,
                            Name = "F2"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000400000000"),
                            Frequency = 174.61000000000001,
                            Name = "F3"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000500000000"),
                            Frequency = 349.23000000000002,
                            Name = "F4"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000600000000"),
                            Frequency = 698.46000000000004,
                            Name = "F5"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000700000000"),
                            Frequency = 1396.9100000000001,
                            Name = "F6"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000800000000"),
                            Frequency = 2793.8299999999999,
                            Name = "F7"
                        },
                        new
                        {
                            ID = new Guid("00000006-0000-0000-0000-000900000000"),
                            Frequency = 5587.6499999999996,
                            Name = "F8"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000100000000"),
                            Frequency = 23.120000000000001,
                            Name = "F#0/Gb0"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000200000000"),
                            Frequency = 46.25,
                            Name = "F#1/Gb1"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000300000000"),
                            Frequency = 92.5,
                            Name = "F#2/Gb2"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000400000000"),
                            Frequency = 185.0,
                            Name = "F#3/Gb3"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000500000000"),
                            Frequency = 369.99000000000001,
                            Name = "F#4/Gb4"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000600000000"),
                            Frequency = 739.99000000000001,
                            Name = "F#5/Gb5"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000700000000"),
                            Frequency = 1479.98,
                            Name = "F#6/Gb6"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000800000000"),
                            Frequency = 2959.96,
                            Name = "F#7/Gb7"
                        },
                        new
                        {
                            ID = new Guid("00000007-0000-0000-0000-000900000000"),
                            Frequency = 5919.9099999999999,
                            Name = "F#8/Gb8"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000100000000"),
                            Frequency = 24.5,
                            Name = "G0"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000200000000"),
                            Frequency = 49.0,
                            Name = "G1"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000300000000"),
                            Frequency = 98.0,
                            Name = "G2"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000400000000"),
                            Frequency = 196.0,
                            Name = "G3"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000500000000"),
                            Frequency = 392.0,
                            Name = "G4"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000600000000"),
                            Frequency = 783.99000000000001,
                            Name = "G5"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000700000000"),
                            Frequency = 1567.98,
                            Name = "G6"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000800000000"),
                            Frequency = 3135.96,
                            Name = "G7"
                        },
                        new
                        {
                            ID = new Guid("00000008-0000-0000-0000-000900000000"),
                            Frequency = 6271.9300000000003,
                            Name = "G8"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000100000000"),
                            Frequency = 25.960000000000001,
                            Name = "G#0/Ab0"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000200000000"),
                            Frequency = 51.909999999999997,
                            Name = "G#1/Ab1"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000300000000"),
                            Frequency = 103.83,
                            Name = "G#2/Ab2"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000400000000"),
                            Frequency = 207.65000000000001,
                            Name = "G#3/Ab3"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000500000000"),
                            Frequency = 415.30000000000001,
                            Name = "G#4/Ab4"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000600000000"),
                            Frequency = 830.61000000000001,
                            Name = "G#5/Ab5"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000700000000"),
                            Frequency = 1661.22,
                            Name = "G#6/Ab6"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000800000000"),
                            Frequency = 3322.4400000000001,
                            Name = "G#7/Ab7"
                        },
                        new
                        {
                            ID = new Guid("00000009-0000-0000-0000-000900000000"),
                            Frequency = 6644.8800000000001,
                            Name = "G#8/Ab8"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000100000000"),
                            Frequency = 27.5,
                            Name = "A0"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000200000000"),
                            Frequency = 55.0,
                            Name = "A1"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000300000000"),
                            Frequency = 110.0,
                            Name = "A2"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000400000000"),
                            Frequency = 220.0,
                            Name = "A3"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000500000000"),
                            Frequency = 440.0,
                            Name = "A4"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000600000000"),
                            Frequency = 880.0,
                            Name = "A5"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000700000000"),
                            Frequency = 1760.0,
                            Name = "A6"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000800000000"),
                            Frequency = 3520.0,
                            Name = "A7"
                        },
                        new
                        {
                            ID = new Guid("0000000a-0000-0000-0000-000900000000"),
                            Frequency = 7040.0,
                            Name = "A8"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000100000000"),
                            Frequency = 29.140000000000001,
                            Name = "A#0/Bb0"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000200000000"),
                            Frequency = 58.270000000000003,
                            Name = "A#1/Bb1"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000300000000"),
                            Frequency = 116.54000000000001,
                            Name = "A#2/Bb2"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000400000000"),
                            Frequency = 233.08000000000001,
                            Name = "A#3/Bb3"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000500000000"),
                            Frequency = 466.16000000000003,
                            Name = "A#4/Bb4"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000600000000"),
                            Frequency = 932.33000000000004,
                            Name = "A#5/Bb5"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000700000000"),
                            Frequency = 1864.6600000000001,
                            Name = "A#6/Bb6"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000800000000"),
                            Frequency = 3729.3099999999999,
                            Name = "A#7/Bb7"
                        },
                        new
                        {
                            ID = new Guid("0000000b-0000-0000-0000-000900000000"),
                            Frequency = 7458.6199999999999,
                            Name = "A#8/Bb8"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000100000000"),
                            Frequency = 30.870000000000001,
                            Name = "B0"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000200000000"),
                            Frequency = 61.740000000000002,
                            Name = "B1"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000300000000"),
                            Frequency = 123.47,
                            Name = "B2"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000400000000"),
                            Frequency = 246.94,
                            Name = "B3"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000500000000"),
                            Frequency = 493.88,
                            Name = "B4"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000600000000"),
                            Frequency = 987.76999999999998,
                            Name = "B5"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000700000000"),
                            Frequency = 1975.53,
                            Name = "B6"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000800000000"),
                            Frequency = 3951.0700000000002,
                            Name = "B7"
                        },
                        new
                        {
                            ID = new Guid("0000000c-0000-0000-0000-000900000000"),
                            Frequency = 7902.1300000000001,
                            Name = "B8"
                        });
                });

            modelBuilder.Entity("Chord_Finder_Core.Model.Chord", b =>
                {
                    b.HasOne("Chord_Finder_Core.Model.ChordType", "ChordType")
                        .WithMany("Chords")
                        .HasForeignKey("ChordTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChordType");
                });

            modelBuilder.Entity("Chord_Finder_Core.Model.ChordType", b =>
                {
                    b.Navigation("Chords");
                });
#pragma warning restore 612, 618
        }
    }
}
