// <auto-generated />
using System;
using Chord_Finder_Core.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chord_Finder_Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250312224428_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Chord_Finder_Core.Model.Chord", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChordTypeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ChordTypeID");

                    b.ToTable("Chords");

                    b.HasData(
                        new
                        {
                            ID = new Guid("82fed50d-0dae-aac4-9774-f3c7e7624104"),
                            ChordTypeID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Name = "C",
                            Notes = "C-E-G"
                        },
                        new
                        {
                            ID = new Guid("72b474ae-0169-4761-ccce-f6524fe8c28b"),
                            ChordTypeID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Name = "Cm",
                            Notes = "C-D#/Eb-G"
                        },
                        new
                        {
                            ID = new Guid("3c598743-003c-203a-8d53-ec3609f9a97c"),
                            ChordTypeID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Name = "Cdim",
                            Notes = "C-D#/Eb-F#/Gb"
                        },
                        new
                        {
                            ID = new Guid("1e5e028a-f076-2180-4c22-31a5b21092ed"),
                            ChordTypeID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Name = "Caug",
                            Notes = "C-E-G#/Ab"
                        },
                        new
                        {
                            ID = new Guid("b6042751-ab84-68a8-b417-814f3fb1bf2e"),
                            ChordTypeID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Name = "C7",
                            Notes = "C-E-G-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("6f8d29f6-d8dd-42ab-e735-54288e354f0a"),
                            ChordTypeID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Name = "Cmaj7",
                            Notes = "C-E-G-B"
                        },
                        new
                        {
                            ID = new Guid("7d67ef01-1f66-d598-434c-f23f87a12db2"),
                            ChordTypeID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Name = "Cmin7",
                            Notes = "C-D#/Eb-G-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("a9760675-74e2-43e1-89b5-5cf74edd654b"),
                            ChordTypeID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Name = "Cø7",
                            Notes = "C-D#/Eb-F#/Gb-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("62daaca6-1a0c-1310-352e-fdf1d3d7cb41"),
                            ChordTypeID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Name = "Cdim7",
                            Notes = "C-D#/Eb-F#/Gb-A"
                        },
                        new
                        {
                            ID = new Guid("bd9211f5-a918-8c4d-b027-110ad79e1768"),
                            ChordTypeID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Name = "Csus2",
                            Notes = "C-D-G"
                        },
                        new
                        {
                            ID = new Guid("52228710-05bb-2512-099c-d23ff0fcace3"),
                            ChordTypeID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Name = "Csus4",
                            Notes = "C-F-G"
                        },
                        new
                        {
                            ID = new Guid("21ba926e-c5da-35d3-904b-403c4ca47b14"),
                            ChordTypeID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Name = "C#/Db",
                            Notes = "C#/Db-F-G#/Ab"
                        },
                        new
                        {
                            ID = new Guid("2bbf9869-3029-870c-829a-2e4ddca36ee9"),
                            ChordTypeID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Name = "C#/Dbm",
                            Notes = "C#/Db-E-G#/Ab"
                        },
                        new
                        {
                            ID = new Guid("9e690599-d7ed-057e-66b3-60ed7eebad1c"),
                            ChordTypeID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Name = "C#/Dbdim",
                            Notes = "C#/Db-E-G"
                        },
                        new
                        {
                            ID = new Guid("ca6db4d2-4648-5fc4-7c79-3aebfbdac8c2"),
                            ChordTypeID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Name = "C#/Dbaug",
                            Notes = "C#/Db-F-A"
                        },
                        new
                        {
                            ID = new Guid("292faf65-a013-5328-171a-eb78e0bbfcfb"),
                            ChordTypeID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Name = "C#/Db7",
                            Notes = "C#/Db-F-G#/Ab-B"
                        },
                        new
                        {
                            ID = new Guid("fc82b277-ac2b-603c-66f8-58dac0262038"),
                            ChordTypeID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Name = "C#/Dbmaj7",
                            Notes = "C#/Db-F-G#/Ab-C"
                        },
                        new
                        {
                            ID = new Guid("a0edc0f2-fbca-2f85-1980-9d065ee3d30a"),
                            ChordTypeID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Name = "C#/Dbmin7",
                            Notes = "C#/Db-E-G#/Ab-B"
                        },
                        new
                        {
                            ID = new Guid("73d4eebe-bdc0-e93f-b60a-99915decc71a"),
                            ChordTypeID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Name = "C#/Dbø7",
                            Notes = "C#/Db-E-G-B"
                        },
                        new
                        {
                            ID = new Guid("8d173d3a-fc16-dc7a-df2e-9968ca6fc9ee"),
                            ChordTypeID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Name = "C#/Dbdim7",
                            Notes = "C#/Db-E-G-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("d8c1f301-e0dc-a06d-d3b7-995aba6b2f24"),
                            ChordTypeID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Name = "C#/Dbsus2",
                            Notes = "C#/Db-D#/Eb-G#/Ab"
                        },
                        new
                        {
                            ID = new Guid("32bdb599-d0ea-8de0-3ed1-25c368cd2399"),
                            ChordTypeID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Name = "C#/Dbsus4",
                            Notes = "C#/Db-F#/Gb-G#/Ab"
                        },
                        new
                        {
                            ID = new Guid("de61ff2b-5cca-be00-2e6b-5d67fd19049a"),
                            ChordTypeID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Name = "D",
                            Notes = "D-F#/Gb-A"
                        },
                        new
                        {
                            ID = new Guid("e3724539-a8e2-2d08-533c-1dd7de6dda0d"),
                            ChordTypeID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Name = "Dm",
                            Notes = "D-F-A"
                        },
                        new
                        {
                            ID = new Guid("167c73c4-0da8-294b-6a7d-75c8ec4fa0a8"),
                            ChordTypeID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Name = "Ddim",
                            Notes = "D-F-G#/Ab"
                        },
                        new
                        {
                            ID = new Guid("cefd1d4d-ced1-0472-bb22-8e7bc3ed73e0"),
                            ChordTypeID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Name = "Daug",
                            Notes = "D-F#/Gb-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("0da342ee-1aa2-8b45-8e29-62c4407fd3eb"),
                            ChordTypeID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Name = "D7",
                            Notes = "D-F#/Gb-A-C"
                        },
                        new
                        {
                            ID = new Guid("194de801-e3e8-2445-065c-0c551e46434e"),
                            ChordTypeID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Name = "Dmaj7",
                            Notes = "D-F#/Gb-A-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("94b60023-9a77-3cce-1144-ff411277e63d"),
                            ChordTypeID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Name = "Dmin7",
                            Notes = "D-F-A-C"
                        },
                        new
                        {
                            ID = new Guid("d78abb6a-bf59-512b-5270-cd17e8201ca7"),
                            ChordTypeID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Name = "Dø7",
                            Notes = "D-F-G#/Ab-C"
                        },
                        new
                        {
                            ID = new Guid("60f2a89a-2275-4029-690c-cdae242b9522"),
                            ChordTypeID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Name = "Ddim7",
                            Notes = "D-F-G#/Ab-B"
                        },
                        new
                        {
                            ID = new Guid("e5475335-48ac-dc67-3e3d-84d40624589f"),
                            ChordTypeID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Name = "Dsus2",
                            Notes = "D-E-A"
                        },
                        new
                        {
                            ID = new Guid("8f344ad8-2d73-685b-2758-a808e2e87e58"),
                            ChordTypeID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Name = "Dsus4",
                            Notes = "D-G-A"
                        },
                        new
                        {
                            ID = new Guid("2b362b88-c423-db16-3699-b7b0c008278a"),
                            ChordTypeID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Name = "D#/Eb",
                            Notes = "D#/Eb-G-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("e5bd16d6-5f2f-5de3-1f43-51141d31e4c2"),
                            ChordTypeID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Name = "D#/Ebm",
                            Notes = "D#/Eb-F#/Gb-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("6e548e78-1b36-8e35-3f90-534276a2fe92"),
                            ChordTypeID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Name = "D#/Ebdim",
                            Notes = "D#/Eb-F#/Gb-A"
                        },
                        new
                        {
                            ID = new Guid("ef4a17a9-a3d3-8a06-620b-8ad5eaf6ceab"),
                            ChordTypeID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Name = "D#/Ebaug",
                            Notes = "D#/Eb-G-B"
                        },
                        new
                        {
                            ID = new Guid("58a0f710-fc54-ac25-b5c2-32805b0c8b5a"),
                            ChordTypeID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Name = "D#/Eb7",
                            Notes = "D#/Eb-G-A#/Bb-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("ab8f61ec-6135-86f8-fe75-1561e445f8e8"),
                            ChordTypeID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Name = "D#/Ebmaj7",
                            Notes = "D#/Eb-G-A#/Bb-D"
                        },
                        new
                        {
                            ID = new Guid("b1bda7f2-10e0-0137-c252-03ca58e3a1f0"),
                            ChordTypeID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Name = "D#/Ebmin7",
                            Notes = "D#/Eb-F#/Gb-A#/Bb-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("cc4a6973-5082-420f-f1e0-c26a668e0463"),
                            ChordTypeID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Name = "D#/Ebø7",
                            Notes = "D#/Eb-F#/Gb-A-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("f5ae5e52-e014-832f-6ae0-a61ae7803492"),
                            ChordTypeID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Name = "D#/Ebdim7",
                            Notes = "D#/Eb-F#/Gb-A-C"
                        },
                        new
                        {
                            ID = new Guid("a4d4b60f-4e6b-4f8a-078c-6ad34e860982"),
                            ChordTypeID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Name = "D#/Ebsus2",
                            Notes = "D#/Eb-F-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("a25d01e2-f473-8c12-f3a5-bfeab89ec20e"),
                            ChordTypeID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Name = "D#/Ebsus4",
                            Notes = "D#/Eb-G#/Ab-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("80fe8d83-e37c-78e3-e674-62d77cac8e04"),
                            ChordTypeID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Name = "E",
                            Notes = "E-G#/Ab-B"
                        },
                        new
                        {
                            ID = new Guid("a3b31824-b523-01b7-e2a2-c1953ccef810"),
                            ChordTypeID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Name = "Em",
                            Notes = "E-G-B"
                        },
                        new
                        {
                            ID = new Guid("c1dd25f5-4740-89c6-1fa0-bf8bafa0dc2f"),
                            ChordTypeID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Name = "Edim",
                            Notes = "E-G-A#/Bb"
                        },
                        new
                        {
                            ID = new Guid("6a0e81ad-1180-fdcd-58d1-338c8379f6d4"),
                            ChordTypeID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Name = "Eaug",
                            Notes = "E-G#/Ab-C"
                        },
                        new
                        {
                            ID = new Guid("561949d3-ede3-00c0-97ad-cbbd6cec06c8"),
                            ChordTypeID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Name = "E7",
                            Notes = "E-G#/Ab-B-D"
                        },
                        new
                        {
                            ID = new Guid("d4fbc7f5-7e7b-5ae3-edcf-588ec65214cb"),
                            ChordTypeID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Name = "Emaj7",
                            Notes = "E-G#/Ab-B-D#/Eb"
                        },
                        new
                        {
                            ID = new Guid("6e848f45-0937-d22c-7869-b24835b89d16"),
                            ChordTypeID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Name = "Emin7",
                            Notes = "E-G-B-D"
                        },
                        new
                        {
                            ID = new Guid("0ec3504d-aa84-198d-5e5c-39a25c4b01f3"),
                            ChordTypeID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Name = "Eø7",
                            Notes = "E-G-A#/Bb-D"
                        },
                        new
                        {
                            ID = new Guid("a4d571dd-0c02-94eb-288a-183c40e491f6"),
                            ChordTypeID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Name = "Edim7",
                            Notes = "E-G-A#/Bb-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("c1ac2103-b769-89ab-a16b-4ffacec20385"),
                            ChordTypeID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Name = "Esus2",
                            Notes = "E-F#/Gb-B"
                        },
                        new
                        {
                            ID = new Guid("c67c4b50-279d-e530-4191-12efffe84ede"),
                            ChordTypeID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Name = "Esus4",
                            Notes = "E-A-B"
                        },
                        new
                        {
                            ID = new Guid("955a6179-8088-e2c1-836c-46ae5629f32d"),
                            ChordTypeID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Name = "F",
                            Notes = "F-A-C"
                        },
                        new
                        {
                            ID = new Guid("586c4bf8-1a3d-4914-547f-3ba7ea12dd04"),
                            ChordTypeID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Name = "Fm",
                            Notes = "F-G#/Ab-C"
                        },
                        new
                        {
                            ID = new Guid("15a3ef3e-9eaa-7169-d6ee-c01657c4ba28"),
                            ChordTypeID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Name = "Fdim",
                            Notes = "F-G#/Ab-B"
                        },
                        new
                        {
                            ID = new Guid("30c4b848-18cc-651a-5b1d-436883d47741"),
                            ChordTypeID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Name = "Faug",
                            Notes = "F-A-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("b8d05a8e-4263-5178-0f43-b31feb950420"),
                            ChordTypeID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Name = "F7",
                            Notes = "F-A-C-D#/Eb"
                        },
                        new
                        {
                            ID = new Guid("cf0b26f5-1e17-5b4a-91ad-5220b5f0c567"),
                            ChordTypeID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Name = "Fmaj7",
                            Notes = "F-A-C-E"
                        },
                        new
                        {
                            ID = new Guid("129a9e43-6a73-ebdb-674c-1cbb3472d376"),
                            ChordTypeID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Name = "Fmin7",
                            Notes = "F-G#/Ab-C-D#/Eb"
                        },
                        new
                        {
                            ID = new Guid("419ece1d-4a0f-32f4-fee2-c05028a73087"),
                            ChordTypeID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Name = "Fø7",
                            Notes = "F-G#/Ab-B-D#/Eb"
                        },
                        new
                        {
                            ID = new Guid("11ae4cfd-4cae-38c6-fdab-5bbc632afea2"),
                            ChordTypeID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Name = "Fdim7",
                            Notes = "F-G#/Ab-B-D"
                        },
                        new
                        {
                            ID = new Guid("1e888e4e-9430-f77d-5829-f877e9e624ef"),
                            ChordTypeID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Name = "Fsus2",
                            Notes = "F-G-C"
                        },
                        new
                        {
                            ID = new Guid("0a599c24-4f62-fd12-d240-19c026723381"),
                            ChordTypeID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Name = "Fsus4",
                            Notes = "F-A#/Bb-C"
                        },
                        new
                        {
                            ID = new Guid("990b9cae-fa42-540c-5612-6f5c23656d1d"),
                            ChordTypeID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Name = "F#/Gb",
                            Notes = "F#/Gb-A#/Bb-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("13aaee76-1059-d87c-4951-d519b0b0a709"),
                            ChordTypeID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Name = "F#/Gbm",
                            Notes = "F#/Gb-A-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("7c3d3093-a168-5f14-9d4d-0a1e28d34711"),
                            ChordTypeID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Name = "F#/Gbdim",
                            Notes = "F#/Gb-A-C"
                        },
                        new
                        {
                            ID = new Guid("6bd46feb-cacc-9236-11f0-afc713892088"),
                            ChordTypeID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Name = "F#/Gbaug",
                            Notes = "F#/Gb-A#/Bb-D"
                        },
                        new
                        {
                            ID = new Guid("07f4b5fa-d3a5-8513-3b1c-4e9f31dcd23e"),
                            ChordTypeID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Name = "F#/Gb7",
                            Notes = "F#/Gb-A#/Bb-C#/Db-E"
                        },
                        new
                        {
                            ID = new Guid("18273616-0bca-399a-58e9-3488d5124179"),
                            ChordTypeID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Name = "F#/Gbmaj7",
                            Notes = "F#/Gb-A#/Bb-C#/Db-F"
                        },
                        new
                        {
                            ID = new Guid("ad941816-1545-b96a-09f8-21c29481bbd4"),
                            ChordTypeID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Name = "F#/Gbmin7",
                            Notes = "F#/Gb-A-C#/Db-E"
                        },
                        new
                        {
                            ID = new Guid("c5460f74-9ae4-40e2-0b28-2c10e5eb3174"),
                            ChordTypeID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Name = "F#/Gbø7",
                            Notes = "F#/Gb-A-C-E"
                        },
                        new
                        {
                            ID = new Guid("e67dd7e8-fd68-7932-f73a-e6908356b14e"),
                            ChordTypeID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Name = "F#/Gbdim7",
                            Notes = "F#/Gb-A-C-D#/Eb"
                        },
                        new
                        {
                            ID = new Guid("277a6339-8854-786f-61fc-dc35ab8101bd"),
                            ChordTypeID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Name = "F#/Gbsus2",
                            Notes = "F#/Gb-G#/Ab-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("cf1c76f7-6aa6-5581-56b1-887808744dcf"),
                            ChordTypeID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Name = "F#/Gbsus4",
                            Notes = "F#/Gb-B-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("a794c569-7ed9-0c82-e4c0-573aa61d32d6"),
                            ChordTypeID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Name = "G",
                            Notes = "G-B-D"
                        },
                        new
                        {
                            ID = new Guid("0e2be71a-6bbb-e01d-2c2c-ef94e4eb1319"),
                            ChordTypeID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Name = "Gm",
                            Notes = "G-A#/Bb-D"
                        },
                        new
                        {
                            ID = new Guid("2cae58c2-e790-20d7-9e30-94c177ea64e6"),
                            ChordTypeID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Name = "Gdim",
                            Notes = "G-A#/Bb-C#/Db"
                        },
                        new
                        {
                            ID = new Guid("3525a0e0-d15f-db65-cba4-aeb5ced7c803"),
                            ChordTypeID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Name = "Gaug",
                            Notes = "G-B-D#/Eb"
                        },
                        new
                        {
                            ID = new Guid("f1eb3b4f-ffe2-3aa0-aa39-942838baf36f"),
                            ChordTypeID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Name = "G7",
                            Notes = "G-B-D-F"
                        },
                        new
                        {
                            ID = new Guid("7b33dd78-c6e2-9ad6-06a7-696fcffc9cd9"),
                            ChordTypeID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Name = "Gmaj7",
                            Notes = "G-B-D-F#/Gb"
                        },
                        new
                        {
                            ID = new Guid("e6fc459f-e76c-3110-7106-88475ce6bf63"),
                            ChordTypeID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Name = "Gmin7",
                            Notes = "G-A#/Bb-D-F"
                        },
                        new
                        {
                            ID = new Guid("c30b5998-570a-d0be-fcf6-da9f450dd035"),
                            ChordTypeID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Name = "Gø7",
                            Notes = "G-A#/Bb-C#/Db-F"
                        },
                        new
                        {
                            ID = new Guid("2255d3eb-03ec-c352-14b9-6068067bb05d"),
                            ChordTypeID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Name = "Gdim7",
                            Notes = "G-A#/Bb-C#/Db-E"
                        },
                        new
                        {
                            ID = new Guid("bbc52a79-6425-6bda-da4d-8282d0d4183e"),
                            ChordTypeID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Name = "Gsus2",
                            Notes = "G-A-D"
                        },
                        new
                        {
                            ID = new Guid("d8c34eed-47e4-41a5-a893-81be91f4b038"),
                            ChordTypeID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Name = "Gsus4",
                            Notes = "G-C-D"
                        });
                });

            modelBuilder.Entity("Chord_Finder_Core.Model.ChordType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ChordTypes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("bb3fb046-88cd-a588-917d-3901f3fefa6e"),
                            Description = "A chord with a root, major third, and perfect fifth.",
                            Name = "Major"
                        },
                        new
                        {
                            ID = new Guid("7e70584c-804f-7f03-8fd8-afc8da686c34"),
                            Description = "A chord with a root, minor third, and perfect fifth.",
                            Name = "Minor"
                        },
                        new
                        {
                            ID = new Guid("61dc65b9-01e5-ef2d-b705-2eae57e50c7a"),
                            Description = "A chord with a root, minor third, and diminished fifth.",
                            Name = "Diminished"
                        },
                        new
                        {
                            ID = new Guid("e84bf7ba-fdfa-2ed6-1b75-47da3e510c9f"),
                            Description = "A chord with a root, major third, and augmented fifth.",
                            Name = "Augmented"
                        },
                        new
                        {
                            ID = new Guid("a73cb2f1-78f4-c392-d35e-37112fa14f03"),
                            Description = "A chord with a root, major third, perfect fifth, and minor seventh.",
                            Name = "Dominant Seventh"
                        },
                        new
                        {
                            ID = new Guid("055cb057-5bbb-f872-73c2-4c18054c968f"),
                            Description = "A chord with a root, major third, perfect fifth, and major seventh.",
                            Name = "Major Seventh"
                        },
                        new
                        {
                            ID = new Guid("5e61df70-0100-e20a-69c8-d092f1209372"),
                            Description = "A chord with a root, minor third, perfect fifth, and minor seventh.",
                            Name = "Minor Seventh"
                        },
                        new
                        {
                            ID = new Guid("b2197772-84d5-1d61-ec79-2862e69b7678"),
                            Description = "A chord with a root, minor third, diminished fifth, and minor seventh.",
                            Name = "Half-Diminished"
                        },
                        new
                        {
                            ID = new Guid("b8530661-15ed-a4d3-99f8-20d024f8a44a"),
                            Description = "A chord with a root, minor third, diminished fifth, and diminished seventh.",
                            Name = "Diminished Seventh"
                        },
                        new
                        {
                            ID = new Guid("e076fa8d-2f8b-94d7-fedf-d8b34a8f126a"),
                            Description = "A chord with a root, major second, and perfect fifth.",
                            Name = "Suspended Second"
                        },
                        new
                        {
                            ID = new Guid("595380d4-1d67-7bf7-2887-c358962e5338"),
                            Description = "A chord with a root, perfect fourth, and perfect fifth.",
                            Name = "Suspended Fourth"
                        });
                });

            modelBuilder.Entity("Chord_Finder_Core.Model.Note", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("Frequency")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("e6375fbd-0f6a-e8fe-9e4e-1db98b845cb4"),
                            Frequency = 16.350000000000001,
                            Name = "C0"
                        },
                        new
                        {
                            ID = new Guid("9614b645-75f2-daee-24ff-7b7874645184"),
                            Frequency = 32.700000000000003,
                            Name = "C1"
                        },
                        new
                        {
                            ID = new Guid("87e2941f-dd13-3b18-f9fe-59aa1e4405e0"),
                            Frequency = 65.409999999999997,
                            Name = "C2"
                        },
                        new
                        {
                            ID = new Guid("509b13da-53c2-458a-0b79-dd9b2823fa3c"),
                            Frequency = 130.81,
                            Name = "C3"
                        },
                        new
                        {
                            ID = new Guid("32cdfc52-4522-d4a6-e118-62ca615bfe59"),
                            Frequency = 261.63,
                            Name = "C4"
                        },
                        new
                        {
                            ID = new Guid("6474bc3d-f3e3-d37e-751b-adb69144c1a1"),
                            Frequency = 523.25,
                            Name = "C5"
                        },
                        new
                        {
                            ID = new Guid("2c2c045b-9569-dabc-1e36-a0fc150010e9"),
                            Frequency = 1046.5,
                            Name = "C6"
                        },
                        new
                        {
                            ID = new Guid("f3f50a00-06e3-d40f-5ad5-4ab482520476"),
                            Frequency = 2093.0,
                            Name = "C7"
                        },
                        new
                        {
                            ID = new Guid("7fa1f30d-9152-895e-f9e0-3f205d4befbf"),
                            Frequency = 4186.0100000000002,
                            Name = "C8"
                        },
                        new
                        {
                            ID = new Guid("92ed3e7f-7c47-2a69-cf9f-1022d0f10ec1"),
                            Frequency = 17.32,
                            Name = "C#0/Db0"
                        },
                        new
                        {
                            ID = new Guid("0745aa73-fe80-ffcf-6f83-2c0152c8b854"),
                            Frequency = 34.649999999999999,
                            Name = "C#1/Db1"
                        },
                        new
                        {
                            ID = new Guid("67d2df14-39a5-7f28-03fe-9b9b2e7dbbbc"),
                            Frequency = 69.299999999999997,
                            Name = "C#2/Db2"
                        },
                        new
                        {
                            ID = new Guid("86d591ca-d1b2-3f23-cb7b-013ed97525b8"),
                            Frequency = 138.59,
                            Name = "C#3/Db3"
                        },
                        new
                        {
                            ID = new Guid("55080674-2dc5-b2b0-b7a0-d5fe53aff267"),
                            Frequency = 277.18000000000001,
                            Name = "C#4/Db4"
                        },
                        new
                        {
                            ID = new Guid("fea2b844-9c1d-9460-3523-b3e54873be76"),
                            Frequency = 554.37,
                            Name = "C#5/Db5"
                        },
                        new
                        {
                            ID = new Guid("f3ad729a-f5ba-394c-05c1-d7114c4c6a39"),
                            Frequency = 1108.73,
                            Name = "C#6/Db6"
                        },
                        new
                        {
                            ID = new Guid("aa02a0bc-86f4-bfca-fbc0-e99eb0a43231"),
                            Frequency = 2217.46,
                            Name = "C#7/Db7"
                        },
                        new
                        {
                            ID = new Guid("f3d90171-b9fe-d300-e6af-baf175248690"),
                            Frequency = 4434.9200000000001,
                            Name = "C#8/Db8"
                        },
                        new
                        {
                            ID = new Guid("6f168f05-a946-72ae-95ff-0a89bfc14d06"),
                            Frequency = 18.350000000000001,
                            Name = "D0"
                        },
                        new
                        {
                            ID = new Guid("229e40f8-b4f1-2bb5-2d28-5c3eec39c120"),
                            Frequency = 36.710000000000001,
                            Name = "D1"
                        },
                        new
                        {
                            ID = new Guid("c549ab0d-baf1-eced-4392-ded46052eb43"),
                            Frequency = 73.420000000000002,
                            Name = "D2"
                        },
                        new
                        {
                            ID = new Guid("14b4b091-6d17-d4f7-a455-8f0517aee58a"),
                            Frequency = 146.83000000000001,
                            Name = "D3"
                        },
                        new
                        {
                            ID = new Guid("28c4b304-1135-180d-c7de-98387d1d7472"),
                            Frequency = 293.66000000000003,
                            Name = "D4"
                        },
                        new
                        {
                            ID = new Guid("4bd07a5f-214b-ea40-c3eb-9032f6a29578"),
                            Frequency = 587.33000000000004,
                            Name = "D5"
                        },
                        new
                        {
                            ID = new Guid("6fb849dd-46ba-bb47-1dad-2d5b321ab6cc"),
                            Frequency = 1174.6600000000001,
                            Name = "D6"
                        },
                        new
                        {
                            ID = new Guid("bff34eae-5455-ead1-f8a6-c44af625430a"),
                            Frequency = 2349.3200000000002,
                            Name = "D7"
                        },
                        new
                        {
                            ID = new Guid("0f466fff-956c-8c2a-7cab-fecb8fadedac"),
                            Frequency = 4698.6300000000001,
                            Name = "D8"
                        },
                        new
                        {
                            ID = new Guid("012ffe52-b50a-a299-52a0-fc89fc2a3160"),
                            Frequency = 19.449999999999999,
                            Name = "D#0/Eb0"
                        },
                        new
                        {
                            ID = new Guid("2fdc4b71-b716-61e1-a218-682b62415b8a"),
                            Frequency = 38.890000000000001,
                            Name = "D#1/Eb1"
                        },
                        new
                        {
                            ID = new Guid("728ae2d0-f197-7502-6e77-9ac92b03e29d"),
                            Frequency = 77.780000000000001,
                            Name = "D#2/Eb2"
                        },
                        new
                        {
                            ID = new Guid("0a202004-c934-a5a1-0438-3a5cb0395f6e"),
                            Frequency = 155.56,
                            Name = "D#3/Eb3"
                        },
                        new
                        {
                            ID = new Guid("2147d5f3-6154-35b6-157a-275fbd818b98"),
                            Frequency = 311.13,
                            Name = "D#4/Eb4"
                        },
                        new
                        {
                            ID = new Guid("fd9ea151-b9de-f0da-9106-14164ce76bfa"),
                            Frequency = 622.25,
                            Name = "D#5/Eb5"
                        },
                        new
                        {
                            ID = new Guid("fe57aca4-13ae-090b-af7c-671d247a6836"),
                            Frequency = 1244.51,
                            Name = "D#6/Eb6"
                        },
                        new
                        {
                            ID = new Guid("337a9e29-5551-7f63-b3ca-bc65b16fae28"),
                            Frequency = 2489.02,
                            Name = "D#7/Eb7"
                        },
                        new
                        {
                            ID = new Guid("6d24b5fa-22e6-27e5-76a8-8a70833f295e"),
                            Frequency = 4978.0299999999997,
                            Name = "D#8/Eb8"
                        },
                        new
                        {
                            ID = new Guid("321c76b1-c3fe-28d9-3b0c-6f2b304482e8"),
                            Frequency = 20.600000000000001,
                            Name = "E0"
                        },
                        new
                        {
                            ID = new Guid("05e96844-a220-f783-f9f9-8e82fc1d2098"),
                            Frequency = 41.200000000000003,
                            Name = "E1"
                        },
                        new
                        {
                            ID = new Guid("71116917-8b23-5bfb-4d35-f4ddda4c2c9d"),
                            Frequency = 82.409999999999997,
                            Name = "E2"
                        },
                        new
                        {
                            ID = new Guid("7efc446d-7426-b8ce-bdc0-4a054e5613a2"),
                            Frequency = 164.81,
                            Name = "E3"
                        },
                        new
                        {
                            ID = new Guid("666ffc27-b103-0b7f-d92e-2a09319b3282"),
                            Frequency = 329.63,
                            Name = "E4"
                        },
                        new
                        {
                            ID = new Guid("e8b66d03-c404-401b-0975-2e057d0afb44"),
                            Frequency = 659.25,
                            Name = "E5"
                        },
                        new
                        {
                            ID = new Guid("4fa194d2-5b84-1347-b121-0a3771e5481a"),
                            Frequency = 1318.51,
                            Name = "E6"
                        },
                        new
                        {
                            ID = new Guid("73f3600a-6f17-12e3-375f-a814aff40a3f"),
                            Frequency = 2637.02,
                            Name = "E7"
                        },
                        new
                        {
                            ID = new Guid("d4bf6a6e-f7dd-9588-7c94-7c6baf985d4c"),
                            Frequency = 5274.04,
                            Name = "E8"
                        },
                        new
                        {
                            ID = new Guid("f1d78d9c-c473-b74d-f560-d140dabf4da2"),
                            Frequency = 21.829999999999998,
                            Name = "F0"
                        },
                        new
                        {
                            ID = new Guid("f5551cdf-4812-5163-a811-7392fe875fd9"),
                            Frequency = 43.649999999999999,
                            Name = "F1"
                        },
                        new
                        {
                            ID = new Guid("1f1f3639-34b8-f52b-7629-558183c0335f"),
                            Frequency = 87.310000000000002,
                            Name = "F2"
                        },
                        new
                        {
                            ID = new Guid("0e968dbe-f3d0-61a9-1b0f-912d1759e22d"),
                            Frequency = 174.61000000000001,
                            Name = "F3"
                        },
                        new
                        {
                            ID = new Guid("01dce9b3-66e3-52f0-9c2b-aa7f2dfc32f0"),
                            Frequency = 349.23000000000002,
                            Name = "F4"
                        },
                        new
                        {
                            ID = new Guid("4201c61e-3620-a0bb-c059-f88a7b35dd96"),
                            Frequency = 698.46000000000004,
                            Name = "F5"
                        },
                        new
                        {
                            ID = new Guid("8790cd7c-b104-1e60-52e1-3f082bbf63c8"),
                            Frequency = 1396.9100000000001,
                            Name = "F6"
                        },
                        new
                        {
                            ID = new Guid("a06132c8-cb82-8bea-b0a1-b86a9277f41f"),
                            Frequency = 2793.8299999999999,
                            Name = "F7"
                        },
                        new
                        {
                            ID = new Guid("ef76bccb-bd0d-7c5a-14b5-bfecb61055b4"),
                            Frequency = 5587.6499999999996,
                            Name = "F8"
                        },
                        new
                        {
                            ID = new Guid("fe6ba18c-31e2-b5ad-5fa2-b99fbc5e783e"),
                            Frequency = 23.120000000000001,
                            Name = "F#0/Gb0"
                        },
                        new
                        {
                            ID = new Guid("8dccf8b6-aa79-716b-6d7c-496ee6fa6d6c"),
                            Frequency = 46.25,
                            Name = "F#1/Gb1"
                        },
                        new
                        {
                            ID = new Guid("10ac04b3-9c46-6dcf-5a8d-80462d2e1e96"),
                            Frequency = 92.5,
                            Name = "F#2/Gb2"
                        },
                        new
                        {
                            ID = new Guid("bb66b225-af27-5928-7a3e-773218b7219a"),
                            Frequency = 185.0,
                            Name = "F#3/Gb3"
                        },
                        new
                        {
                            ID = new Guid("53f09082-4abc-1835-1a67-512411408777"),
                            Frequency = 369.99000000000001,
                            Name = "F#4/Gb4"
                        },
                        new
                        {
                            ID = new Guid("d0b41f7e-d8e6-aaec-3ab0-ada37e84a3a6"),
                            Frequency = 739.99000000000001,
                            Name = "F#5/Gb5"
                        },
                        new
                        {
                            ID = new Guid("2f87f580-9891-a94c-4f55-59677923a8bf"),
                            Frequency = 1479.98,
                            Name = "F#6/Gb6"
                        },
                        new
                        {
                            ID = new Guid("c203ff44-4571-7830-1a1e-d124f5905f19"),
                            Frequency = 2959.96,
                            Name = "F#7/Gb7"
                        },
                        new
                        {
                            ID = new Guid("d82ed794-c832-6af0-f5a1-6f932da8562d"),
                            Frequency = 5919.9099999999999,
                            Name = "F#8/Gb8"
                        },
                        new
                        {
                            ID = new Guid("4c6cb635-e9bd-a09a-1eba-8775d819b4c6"),
                            Frequency = 24.5,
                            Name = "G0"
                        },
                        new
                        {
                            ID = new Guid("89dfbe63-d95d-dfca-d801-bd07789d4cab"),
                            Frequency = 49.0,
                            Name = "G1"
                        },
                        new
                        {
                            ID = new Guid("e7c292d2-9f00-8f29-da6d-b24aa2ad645c"),
                            Frequency = 98.0,
                            Name = "G2"
                        },
                        new
                        {
                            ID = new Guid("0c6cb583-ffe2-ac56-0754-2f501910cc67"),
                            Frequency = 196.0,
                            Name = "G3"
                        },
                        new
                        {
                            ID = new Guid("222788b6-4dcb-78b3-22de-61c731b00238"),
                            Frequency = 392.0,
                            Name = "G4"
                        },
                        new
                        {
                            ID = new Guid("c2301d9a-4686-9d60-3f90-088f3fc1af9a"),
                            Frequency = 783.99000000000001,
                            Name = "G5"
                        },
                        new
                        {
                            ID = new Guid("267c2cb1-3aa7-112a-5900-67086586ac35"),
                            Frequency = 1567.98,
                            Name = "G6"
                        },
                        new
                        {
                            ID = new Guid("78f8a408-3b95-18f7-cb14-3640d2fcdc08"),
                            Frequency = 3135.96,
                            Name = "G7"
                        },
                        new
                        {
                            ID = new Guid("28158a95-490b-61d6-fb21-0a1afb12f24c"),
                            Frequency = 6271.9300000000003,
                            Name = "G8"
                        },
                        new
                        {
                            ID = new Guid("8bc5cf9a-63c9-a130-8101-a41c50a2ce4e"),
                            Frequency = 25.960000000000001,
                            Name = "G#0/Ab0"
                        },
                        new
                        {
                            ID = new Guid("0895fab3-5c31-b626-c469-770a3507a2c9"),
                            Frequency = 51.909999999999997,
                            Name = "G#1/Ab1"
                        },
                        new
                        {
                            ID = new Guid("e49a595e-967a-c96e-c095-5309a42fdd40"),
                            Frequency = 103.83,
                            Name = "G#2/Ab2"
                        },
                        new
                        {
                            ID = new Guid("9be378f9-6c5c-309c-afb1-3a3973f9cfaf"),
                            Frequency = 207.65000000000001,
                            Name = "G#3/Ab3"
                        },
                        new
                        {
                            ID = new Guid("fdc2da21-443f-fc9f-c09b-1ed8e7262601"),
                            Frequency = 415.30000000000001,
                            Name = "G#4/Ab4"
                        },
                        new
                        {
                            ID = new Guid("f60cae08-217c-8936-ff2f-0c7d0c32d704"),
                            Frequency = 830.61000000000001,
                            Name = "G#5/Ab5"
                        },
                        new
                        {
                            ID = new Guid("7ca71c23-e9fe-cb2f-faa4-400ec140e3b1"),
                            Frequency = 1661.22,
                            Name = "G#6/Ab6"
                        },
                        new
                        {
                            ID = new Guid("ad49df17-3411-3ab3-afa3-b9cdc31417db"),
                            Frequency = 3322.4400000000001,
                            Name = "G#7/Ab7"
                        },
                        new
                        {
                            ID = new Guid("6400d891-2f6a-cbe7-ea66-e7067af96f27"),
                            Frequency = 6644.8800000000001,
                            Name = "G#8/Ab8"
                        },
                        new
                        {
                            ID = new Guid("b6a81f5d-b02e-7b88-e498-fc2b931e481c"),
                            Frequency = 27.5,
                            Name = "A0"
                        },
                        new
                        {
                            ID = new Guid("db6734b3-568b-ccd0-8eb2-30a0411ca8fd"),
                            Frequency = 55.0,
                            Name = "A1"
                        },
                        new
                        {
                            ID = new Guid("aaa051ca-9124-6810-b997-8dc1772c052d"),
                            Frequency = 110.0,
                            Name = "A2"
                        },
                        new
                        {
                            ID = new Guid("88072522-7c92-43a7-983a-c8c42d151ecf"),
                            Frequency = 220.0,
                            Name = "A3"
                        },
                        new
                        {
                            ID = new Guid("192a34ed-e2b2-de29-6ab0-f482d0ee05eb"),
                            Frequency = 440.0,
                            Name = "A4"
                        },
                        new
                        {
                            ID = new Guid("efb1fb2c-6831-6e9e-c701-7e723016e2bd"),
                            Frequency = 880.0,
                            Name = "A5"
                        },
                        new
                        {
                            ID = new Guid("fb0dafd5-f6b4-98b8-e187-04a0cc7ca9e9"),
                            Frequency = 1760.0,
                            Name = "A6"
                        },
                        new
                        {
                            ID = new Guid("ee935a32-e778-1a61-ccf2-5e39fbe7c7bb"),
                            Frequency = 3520.0,
                            Name = "A7"
                        },
                        new
                        {
                            ID = new Guid("7111bfbe-c92c-8578-8109-4e8e91d3c574"),
                            Frequency = 7040.0,
                            Name = "A8"
                        },
                        new
                        {
                            ID = new Guid("d38dc0eb-5f4e-a663-7a5c-53c42d2501ed"),
                            Frequency = 29.140000000000001,
                            Name = "A#0/Bb0"
                        },
                        new
                        {
                            ID = new Guid("6caa5e50-393a-0bd6-e93a-8c67c2fb8d13"),
                            Frequency = 58.270000000000003,
                            Name = "A#1/Bb1"
                        },
                        new
                        {
                            ID = new Guid("97f305f4-e324-ef64-6499-f6f2c127b8b8"),
                            Frequency = 116.54000000000001,
                            Name = "A#2/Bb2"
                        },
                        new
                        {
                            ID = new Guid("55f51c10-66c3-4b7b-2714-5272565ae2b6"),
                            Frequency = 233.08000000000001,
                            Name = "A#3/Bb3"
                        },
                        new
                        {
                            ID = new Guid("0b77ddbc-24d8-a08b-4902-108037a9bbf0"),
                            Frequency = 466.16000000000003,
                            Name = "A#4/Bb4"
                        },
                        new
                        {
                            ID = new Guid("a02af404-6b31-7c2b-7248-4fde98cba1ed"),
                            Frequency = 932.33000000000004,
                            Name = "A#5/Bb5"
                        },
                        new
                        {
                            ID = new Guid("37a1aca8-4b36-8427-4b53-a58d06e1240f"),
                            Frequency = 1864.6600000000001,
                            Name = "A#6/Bb6"
                        },
                        new
                        {
                            ID = new Guid("577301ea-be8c-0134-2155-a91907c4fc28"),
                            Frequency = 3729.3099999999999,
                            Name = "A#7/Bb7"
                        },
                        new
                        {
                            ID = new Guid("024a06fd-eeeb-b1de-a8aa-400aaa2a9b5f"),
                            Frequency = 7458.6199999999999,
                            Name = "A#8/Bb8"
                        },
                        new
                        {
                            ID = new Guid("30acc647-e77c-7489-9184-f69e8486c4bb"),
                            Frequency = 30.870000000000001,
                            Name = "B0"
                        },
                        new
                        {
                            ID = new Guid("e2186f68-576f-3dfb-af59-706e510e1ffb"),
                            Frequency = 61.740000000000002,
                            Name = "B1"
                        },
                        new
                        {
                            ID = new Guid("4bb48c45-5456-e760-95da-8be7efa912a3"),
                            Frequency = 123.47,
                            Name = "B2"
                        },
                        new
                        {
                            ID = new Guid("78cbf586-c496-ec7b-b7fd-e9225feb95e7"),
                            Frequency = 246.94,
                            Name = "B3"
                        },
                        new
                        {
                            ID = new Guid("311468b6-4c5a-e01d-bdfa-f523276e025f"),
                            Frequency = 493.88,
                            Name = "B4"
                        },
                        new
                        {
                            ID = new Guid("e50bf423-59eb-a5a4-68e0-2952a0cff88e"),
                            Frequency = 987.76999999999998,
                            Name = "B5"
                        },
                        new
                        {
                            ID = new Guid("765b6a5d-be26-9fb3-5bac-da4a1b49336f"),
                            Frequency = 1975.53,
                            Name = "B6"
                        },
                        new
                        {
                            ID = new Guid("8a5586e3-2e82-a300-2faf-357766072d6e"),
                            Frequency = 3951.0700000000002,
                            Name = "B7"
                        },
                        new
                        {
                            ID = new Guid("bc028248-abbe-ef88-1ef5-a307fa01ae15"),
                            Frequency = 7902.1300000000001,
                            Name = "B8"
                        });
                });

            modelBuilder.Entity("Chord_Finder_Core.Model.Chord", b =>
                {
                    b.HasOne("Chord_Finder_Core.Model.ChordType", "ChordType")
                        .WithMany("Chords")
                        .HasForeignKey("ChordTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChordType");
                });

            modelBuilder.Entity("Chord_Finder_Core.Model.ChordType", b =>
                {
                    b.Navigation("Chords");
                });
#pragma warning restore 612, 618
        }
    }
}
